### ISSUE TITLE
Can not get correct value in db_client_test.cc

### ISSUE THREAD

**Issue by daokunhu** [DICL/listdb#8]
The values inserted in ListDB are `10, 1, 5` in  `b_client_test.cc`, but the outputs of `db_client_test.cc` are  "281474982233184 281474982249696 281474982266208". 
It seems  ListDB can not get the correct value.

**Comment by wonbaekimys** [comment]
Thank you for finding the problem.
The reason is that db_client_test.cc that you used was outdated. The current version of DBClient::Get returns pmem address of the log when it finds a key from a MemTable. You can see the correct value by
`std::cout << *(PmemPtr::Decode<uint64_t>(val_read)) << std::endl;`
I just pushed a new version of db_client_test.cc.
